CREATE TABLE PUNTO_GEOGRAFICO (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(4000),
    DIRECCION VARCHAR2(4000),
    LATITUD FLOAT ,
    LONGITUD FLOAT ,    
    CONSTRAINT FK_PUNTO_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);
CREATE TABLE REVISION(
    ID NUMBER PRIMARY KEY,
    CALIFICACION INTEGER, 
    COMENTARIO VARCHAR2(4000),
    FECHA DATE,
    EMISOR_TIPO VARCHAR(20) NOT NULL CHECK (EMISOR_TIPO IN('USUARIO_SERVICIO','CONDUCTOR' )),
    CONSTRAINT FK_REVISION_VIAJE FOREIGN KEY (ID) REFERENCES VIAJE(ID),
    CONSTRAINT FK_REVISION_USUARIO_SERVICIO FOREIGN KEY (ID) REFERENCES USUARIO_SERVICIO(ID),
    CONSTRAINT FK_REVISION_USUARIO_CONDUCTOR FOREIGN KEY (ID) REFERENCES USUARIO_CONDUCTOR(ID)   
);
CREATE TABLE VIAJE(
    ID NUMBER PRIMARY KEY,
    HORA_INICIO DATE,
    HORA_FIN DATE,
    DISTANCIA_KM DECIMAL,
    COSTO_TOTAL DECIMAL,
    CONSTRAINT FK_VIAJE_USUARIO_SERVICIO FOREIGN KEY (ID) REFERENCES USUARIO_SERVICIO(ID),
    CONSTRAINT FK_VIAJE_USUARIO_CONDUCTOR FOREIGN KEY (ID) REFERENCES USUARIO_CONDUCTOR(ID),
    CONSTRAINT FK_VIAJE_VEHICULO FOREIGN KEY (ID) REFERENCES VEHICULO(ID),
    CONSTRAINT FK_VIAJE_PUNTO FOREIGN KEY (ID) REFERENCES PUNTO_GEOGRAFICO(ID)
);
CREATE TABLE VEHICULO(
    ID NUMBER PRIMARY KEY,
    TIPO VARCHAR(20) NOT NULL CHECK(TIPO IN('CARRO','CAMIONETA','MOTOCICLETA')),
    MARCA VARCHAR2(4000) NOT NULL,
    MODELO VARCHAR2(4000) NOT NULL,
    COLOR VARCHAR2(4000) NOT NULL,
    PLACA VARCHAR2(4000) NOT NULL,
    CIUDAD_EXPEDICION VARCHAR2(4000) NOT NULL,
    CAPACIDAD_PASAJEROS INTEGER NOT NULL,
    ACTIVO CHAR(1) NOT NULL,
    NIVEL VARCHAR(20) CHECK(NIVEL IN('ESTANDAR', 'COMFORT', 'LARGE')),    
    CONSTRAINT FK_VEHICULO_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);
CREATE TABLE CIUDAD(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(4000),
    CONSTRAINT FK_CIUDAD_PUNTO FOREIGN KEY (ID) REFERENCES PUNTO_GEOGRAFICO(ID),
    CONSTRAINT FK_CIUDAD_DISPONIBILIDAD FOREIGN KEY (ID) REFERENCES DISPONIBILIDAD(ID)
);
CREATE TABLE SERVICIO(
    ID NUMBER PRIMARY KEY,
    ES_PASAJEROS CHAR(1),
    ES_COMIDA CHAR(1),
    ES_MERCANCIA CHAR(1),
    CONSTRAINT FK_SERVICIO_DISPONIBILIDAD FOREIGN KEY (ID) REFERENCES DISPONIBILIDAD(ID)  
);
CREATE TABLE DISPONIBILIDAD(
    ID NUMBER PRIMARY KEY,
    DIA_SEMANA INTEGER,
    HORA_INICIO TIME,
    HORA_FIN TIME,    
    CONSTRAINT FK_DISPONIBILIDAD_CONDUCTOR FOREIGN KEY (ID) REFERENCES USUARIO_CONDUCTOR(ID_USUARIO),
    CONSTRAINT FK_DISPONIBILIDAD_VEHICULO FOREIGN KEY (ID) REFERENCES VEHICULO(ID)
);
CREATE TABLE USUARIO(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(4000),
    EMAIL VARCHAR2(40000),
    CELULAR INTEGER,
    CEDULA INTEGER,
    FECHA_REGISTRO DATE    
);
CREATE TABLE USUARIO_CONDUCTOR(
    ID NUMBER PRIMARY KEY,
    ACTIVO CHAR(1),       
    CONSTRAINT FK_CONDUCTOR_USUARIO FOREIGN KEY (ID) REFERENCES USUARIO(ID)
);
CREATE TABLE USUARIO_SERVICIO(
    ID NUMBER PRIMARY KEY,
    TARJETA_NUMERO INTEGER,
    TARJETA_NOMBRE VARCHAR2(4000),
    TARJETA_VENCIMIENTO DATE,
    TARJETA_CVV INTEGER,
    CONSTRAINT FK_USER_SERVICIO_USUARIO FOREIGN KEY(ID) REFERENCES USUARIO(ID)
);